### ISSUE TITLE
Sample data

### ISSUE THREAD

**Issue by darrylyeo** [darrylyeo/307-Sec-05-Team-3#109]
Follow up to #18. Make a .sql file that creates 5 test users (including an admin) and 15-20 example events from events.calpoly.edu or https://25live.collegenet.com/pro/calpoly#!/home/calendar.

**Comment by darrylyeo** [comment]
Find some events from another college and do the same. Vary the bookmarks as well.

**Comment by darrylyeo** [comment]
Make one of the events "CSC 307 Demos" at the CS building

**Comment by Hunter-Lane** [comment]
### Accounts to use for demo
 * (Member) Username=CampusNowMember , Password = 1234
 * (Admin) Username = CampusNowAdmin, Password = 5678

**Comment by Hunter-Lane** [comment]
### Events to use for demo

 * 4 Sample Cal Poly Hosted events, each posted by the admin account
 * 2 Sample Events posted by the user, one on campus and one at Avila Beach

**Comment by Hunter-Lane** [comment]
### Bookmarks to use for demo

 * Account 'CampusNowMember' has bookmarked 'Mens Tennis' and 'Avila Beach Party'
